{% set version = "v1.1.alpha" %}

package:
  name: libpostal
  version: "{{ version }}"

source:
  git_url: https://github.com/openvenues/libpostal
  git_tag: v1.1-alpha-31-g790e24bc

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - curl
    - autoconf
    - automake
    - libtool
    - {{ compiler('c') }}
    - make
  run:
    - curl

test:
  commands:
    - test -d ${PREFIX}/share/libpostal_data
    - test -d ${PREFIX}/share/libpostal_data/libpostal/address_expansions
    - test -d ${PREFIX}/share/libpostal_data/libpostal/address_parser
    - test -d ${PREFIX}/share/libpostal_data/libpostal/transliteration
    - test -f ${PREFIX}/share/libpostal_data/libpostal/transliteration/transliteration.dat
    - test -f ${PREFIX}/share/libpostal_data/libpostal/address_parser/address_parser_crf.dat
    - test -f ${PREFIX}/share/libpostal_data/libpostal/address_expansions/address_dictionary.dat
    - test -f ${PREFIX}/bin/libpostal_data
    - test -f $PREFIX/lib/libpostal${SHLIB_EXT}

about:
  home: https://github.com/openvenues/libpostal
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: C library for parsing/normalizing street addresses around the world.

extra:
  recipe-maintainers:
    - MichaelMarien
